sudo: required
services:
  - docker

before_install:
  - docker build -t brajeshmodi/Docker-React-image -f Dockerfile.deb .
script:
  - docker run brajeshmodi/Docker-React-image npm run test -- --coverage       
